networks:
  default:
    name: workspace
    driver: bridge

services:

  db:
    networks:
      - default
    image: postgres:15-alpine
    hostname: postgres
    container_name: db
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: forge
    ports:
      - "5432:5432"

  next:
    init: true
    tty: true
    networks:
      - default
    build:
      context: .
      dockerfile: forge/next/Dockerfile
      target: dev
      args:
        NODE_ENV: development
        PORT: 3000
        DATABASE_URL: postgres://user:password@db:5432/forge
    environment:
        - NODE_ENV=development
        - PORT=3000
        - DATABASE_URL=postgres://user:password@db:5432/forge
    image: forge-next:development
    container_name: forge-next-development
    ports:
      - "3000:3000"
    volumes:
      - ./forge/next:/app/forge/next
      - /app/forge/node_modules
      - /app/node_modules
    depends_on:
      - db

volumes:
  db:
